tunnel: aa04f37f-025a-4dbb-8a06-87acf29ff7a2
credentials-file: /etc/cloudflared/creds/credentials.json

ingress:
  - hostname: vault.serhii.link
    service: http://vault:8200
  - service: http_status:404