services:
  portainer:
    ports:
      - "9000:9000"
      - "9443:9443"
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/docker/portainer/data:/data
    restart: unless-stopped

networks:
  edge:
    external: true
