version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: infisical
      POSTGRES_USER: infisical
      POSTGRES_PASSWORD_FILE: /run/infisical-secrets/POSTGRES_PASSWORD
    volumes:
      - /mnt/data/docker/infisical/postgres:/var/lib/postgresql/data
      - /mnt/data/docker/infisical/env:/run/infisical-secrets:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U infisical -d infisical"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /mnt/data/docker/infisical/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  infisical:
    image: infisical/infisical:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - /mnt/data/docker/infisical/env/infisical.env
    ports:
      - "8080:8080"