services:
  samba:
    image: servercontainers/samba
    container_name: samba
    networks:
      lan:
        ipv4_address: 192.168.1.11
    environment:
      - TZ=America/Los_Angeles
      - AVAHI_NAME=Share
    volumes:
      - /mnt/data/samba:/shares
#      - ./smb.conf:/etc/samba/smb.conf:ro
#      - ./config:/etc/samba:ro
#      - /mnt/data/docker/samba/conf/smb.conf:/etc/samba/smb.conf:ro
      - ./stack/samba/config:/etc/samba:ro
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

networks:
  lan:
    external: true
