services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/docker/portainer/data:/data
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    networks:
      lan:
        ipv4_address: 192.168.1.10
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Los_Angeles
    volumes:
#      - /mnt/data/docker/adguard/work:/opt/adguardhome/work
      - /mnt/data/docker/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
  samba:
    image: servercontainers/samba
    container_name: samba
    networks:
      lan:
        ipv4_address: 192.168.1.11
    environment:
      - TZ=America/Los_Angeles
      - AVAHI_NAME=Share
    volumes:
      - /mnt/data/samba:/shares
      - ./smb.conf:/etc/samba/smb.conf:ro
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

networks:
  lan:
    external: true
