services:
  samba:
    image: servercontainers/samba
    container_name: samba
    networks:
      lan_infra:
        ipv4_address: 192.168.1.11
    environment:
      - TZ=America/Los_Angeles
      - AVAHI_NAME=Share
    volumes:
      - /mnt/data/samba:/shares
      - ./smb.conf:/etc/samba/smb.conf:ro
    restart: unless-stopped

networks:
  lan_infra:
    external: true
