services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    networks:
      lan:
        ipv4_address: 192.168.1.10
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/data/docker/adguard/work:/opt/adguardhome/work
      - /mnt/data/docker/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

networks:
  lan:
    external: true