services:
  coolify:
    image: coollabsio/coolify:latest
    container_name: coolify
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/docker/coolify/data:/data
    restart: unless-stopped